//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dreamland
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employer()
        {
            this.Batch = new HashSet<Batch>();
        }
    
        public int tabNum { get; set; }
        public string name { get; set; }
        public System.DateTime dateStartWork { get; set; }
        public int position { get; set; }
        public decimal salary { get; set; }
        public string password { get; set; }
        public Nullable<int> status { get; set; }

        public string TitleStatus
        {
            get
            {
                if (status == null)
                    return "";
                else return Status1.statusname;

            }
        }
        public string TitlePos
        {
            get
            {
                if (Position1 == null)
                    return "";
                else return Position1.Titile;

            }
        }

        public string Stazh
        {
            get
            {
                TimeSpan days = DateTime.Now - dateStartWork;
                int years = days.Days / 365;
                int month = (days.Days - (years * 365)) / 30;
                return $"{years} лет {month} мес.";

            }
        }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batch { get; set; }
        public virtual Position Position1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
